-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 15:50:53 2023
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

-- Disable unique checks, foreign key checks, and set specific SQL mode
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Create or recreate the schema
DROP SCHEMA IF EXISTS `mygame`;
CREATE SCHEMA IF NOT EXISTS `mygame` DEFAULT CHARACTER SET utf8;
USE `mygame`;

-- Create or recreate the results table
DROP TABLE IF EXISTS `mygame`.`results`;
CREATE TABLE IF NOT EXISTS `mygame`.`results` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `exercise` VARCHAR(15) NOT NULL COMMENT 'Description of exercise',
  `pseudo` VARCHAR(50) NOT NULL COMMENT 'Username or pseudonym',
  `date_hour` DATETIME NOT NULL COMMENT 'Date and time of the record',
  `during` TIME NOT NULL COMMENT 'Duration of the exercise',
  `nb_trials` INT NOT NULL COMMENT 'Number of trials',
  `nb_ok` INT NOT NULL COMMENT 'Number of successful trials'
) ENGINE = InnoDB COMMENT 'Table to store game results';

-- Create or recreate the users table
DROP TABLE IF EXISTS `mygame`.`users`;
CREATE TABLE IF NOT EXISTS `mygame`.`users` (
  `username` VARCHAR(25) PRIMARY KEY NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL
) ENGINE = INNODB;

-- Restore original settings
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
